name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.8
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Format
        run: |
          poetry run black --check --diff linz_logger/*
      - name: Lint
        run: |
          poetry run pylint linz_logger/*
      - name: Import Sorting
        run: |
          poetry run isort --check --diff linz_logger/*
      - name: Test
        run: |
          poetry run pytest
