name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.12.3"
      - name: Install
        run: |
          pip install poetry
          poetry install --no-root
      - name: Lint & format
        run: |
          poetry run pre-commit run --all-files
      - name: Test
        run: |
          poetry run pytest
