name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.12.3"
      - name: Install
        run: |
          pip install poetry
          poetry install --no-root
      - name: Format
        run: |
          poetry run black --check --diff linz_logger/*
      - name: Lint
        run: |
          poetry run pylint linz_logger/*
      - name: Import Sorting
        run: |
          poetry run isort --check --diff linz_logger/*
      - name: Test
        run: |
          poetry run pytest
