name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.8
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Format
        run: |
          black logger/** --check --diff
      - name: Lint
        run: |
          pylint logger/**
      - name: Import Sorting
        run: |
          isort -rc logger/** --check --diff
      - name: Test
        run: |
          pytest
