name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12.3"
      - name: Install
        run: |
          pip install poetry
          poetry install --no-root
      - name: Lint & format
        run: |
          poetry run pre-commit run --all-files
      - name: Test
        run: |
          poetry run pytest
