name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: linz
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Lint & format
        run: nix-shell --pure --run 'pre-commit run --all-files'
      - name: Test
        run: nix-shell --pure --run pytest
