name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.12.3"
      - name: Install
        run: |
          pip install poetry
          poetry install --no-root
      - name: Format
        run: |
          poetry run black --check --diff linz_logger/*
      - name: Lint
        run: |
          poetry run pylint linz_logger/*
      - name: Import Sorting
        run: |
          poetry run isort --check --diff linz_logger/*
      - name: Test
        run: |
          poetry run pytest
