name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: 3.8
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Format
        run: |
          poetry run black --check --diff linz_logger/*
      - name: Lint
        run: |
          poetry run pylint linz_logger/*
      - name: Import Sorting
        run: |
          poetry run isort --check --diff linz_logger/*
      - name: Test
        run: |
          poetry run pytest
