name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Format
        run: |
          poetry run black linz_logger/** --check --diff
      - name: Lint
        run: |
          poetry run pylint linz_logger/**
      - name: Import Sorting
        run: |
          poetry run isort linz_logger/** --check --diff
      - name: Test
        run: |
          poetry run pytest
      - name: Publish
        if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'release:')
        run: |
          poetry config pypi-token.pypi ${PYPI_TOKEN}
          poetry build
          poetry publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
