on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e # v4.0.2
        id: release
        with:
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: release-please
    runs-on: ubuntu-22.04
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.12.3"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Set PyPI token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish
